# Generated by Django 5.0.6 on 2024-06-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_imagemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageModel",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
