# Generated by Django 5.0.6 on 2024-06-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_delete_imagemodel_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageComparisonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_1", models.URLField()),
                ("person_2", models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Image",
            new_name="ImageModel",
        ),
    ]
