# Generated by Django 5.0.6 on 2024-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_person_1_imagecomparisonmodel_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecomparisonmodel",
            name="person",
            field=models.ImageField(upload_to=""),
        ),
    ]
